databricks_profile:
  outputs:
    dev:
      type: databricks
      schema: dbt_dev
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      catalog: hive_metastore
  target: dev
